### ISSUE TITLE
Pytest failing

### ISSUE THREAD

**Issue by stephanecollot** [lneisenman/cookiecutter-cython#2]
Hello,

I was trying to run the tests, but it fails, is it normal?
(EDIT, we shouldn't type `pytest` to run the test)

To run the test, I tried: `make test`
But first I had to install some packages (that were not in the requirements file: cython and numpy.
And then I have this error:
```
make test
python setup.py test
Compiling lneisenman/lneisenman.pyx because it changed.
[1/1] Cythonizing lneisenman/lneisenman.pyx
/private/tmp/lol/lneisenman/venv/lib/python2.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /private/tmp/lol/lneisenman/lneisenman/lneisenman.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
creating lneisenman.egg-info
writing requirements to lneisenman.egg-info/requires.txt
writing lneisenman.egg-info/PKG-INFO
writing top-level names to lneisenman.egg-info/top_level.txt
writing dependency_links to lneisenman.egg-info/dependency_links.txt
writing manifest file 'lneisenman.egg-info/SOURCES.txt'
reading manifest file 'lneisenman.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
writing manifest file 'lneisenman.egg-info/SOURCES.txt'
running build_ext
building 'lneisenman.lneisenman' extension
creating build
creating build/temp.xx
creating build/temp.xx/lneisenman
gcc -fno-strict-aliasing -I/xx/xxx/miniconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/private/tmp/lol/lneisenman/venv/lib/python2.7/site-packages/numpy/core/include -I/xx/xx/miniconda2/include/python2.7 -c lneisenman/lneisenman.c -o build/temp.xxx/lneisenman/lneisenman.o
creating build/lib.macosx-10.6-x86_64-2.7
creating build/lib.macosx-10.6-x86_64-2.7/lneisenman
gcc -bundle -undefined dynamic_lookup -L/xx/xxx/miniconda2/lib -arch x86_64 -arch x86_64 build/temp.macosx-xx/lneisenman/lneisenman.o -L/xx/xxx/miniconda2/lib -o build/lib.xx-xx/lneisenman/lneisenman.so
copying build/lib.xx-x/lneisenman/lneisenman.so -> lneisenman
Traceback (most recent call last):
  File "setup.py", line 61, in <module>
    ext_modules=cythonize(extensions),
  File "/private/tmp/lol/lneisenman/venv/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/xx/xx/miniconda/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/xx/xx/miniconda/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/xx/xx/miniconda/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/private/tmp/lol/lneisenman/venv/lib/python2.7/site-packages/setuptools/command/test.py", line 237, in run
    self.run_tests()
  File "/private/tmp/lol/lneisenman/venv/lib/python2.7/site-packages/setuptools/command/test.py", line 259, in run_tests
    exit=False,
  File "/xx/xx/miniconda/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/xx/xx/miniconda/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/xx/xx/miniconda/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/xx/xx/miniconda/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/xx/xx/miniconda/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
ImportError: No module named tests
make: *** [test] Error 1
```

**Comment by lneisenman** [comment]
I never bothered with the tests that came from cloning the repo. All I looked at was whether or not it would generate the template project that I wanted.
